-- Place this file in your railworks plugins folder
-- Usually C:\Program Files (x86)\Steam\steamapps\common\railworks\plugins (for 64 bit windows)
-- or C:\Program Files\Steam\steamapps\common\railworks\plugins (for 32 bit windows)

--The command used to check if a certain control exists or not and if it does
-- retreive its value is:-

-- if Call("*:ControlExists", Name of control, 0) == 1 then
-- variable = Call( "*:GetControlValue", Name of control, 0 )
--end

--This code block as you will see is used throughout the script to retrieve
--the data for each control required and can easily be added to or deleted from.
--I have included in the files 'Railworks EngineData.pdf' which lists all the
--control names I have found along with their min/max/default values.
--I then use the local variable data to store the name of the control followed by a colon
-- and the return value and a new line. The data variable is added to as each control is read
-- throughout the script and at the end of the script we open the plugins/GetData.txt file
-- and write the whole data variable to the file ready for reading into your program.

--A word of warning, be careful with your syntax when editing lua script files because
--the only way you know something is wrong is when the script does not work. That is
--why I have included the line gCurrentTime = Call( "*:GetSimulationTime", 0 ). If your
--script is OK then the line at the end of the textbox display in my C# program will
--display "Current Time = :" followed by the time in seconds counting up. If this line
--is static then there is an error in your script. So my advice is make small changes
--and test your script regularly. 

-------------------  GetData function --------------------
gData = ""
delay = 5 
counter = 3 --Loop counter to only update every number of itterations set bt delay variable
dataread = 0
previousValues = {}
speedoType = 0 -- 0 = none, 1 = MPH, 2 = KPH
MPH = 2.23693629 -- 2.23694 --Convert meters per second to MPH
KPH = 3.60	--Convert meters per second to KPH
delete_Files = 1 --We need to delete the Getdata.txt and sendcommand.txt files on first run so updated data is received

-- Configurable base paths (use absolute paths for RailWorks compatibility)
local BASE_DIR = "C:\\Program Files (x86)\\Steam\\steamapps\\common\\RailWorks\\plugins"
local GETDATA_PATH = BASE_DIR .. "\\GetData.txt"
local SENDCOMMAND_PATH = BASE_DIR .. "\\SendCommand.txt"
local SENDCOMMAND_PATH_LOWER = BASE_DIR .. "\\sendcommand.txt"
local GETDATA_ERROR_PATH = BASE_DIR .. "\\GetData_Error.txt"

function getdata ()
	-- Wrap everything in pcall to catch errors and prevent game crashes
	local success, err = pcall(function()
		-- Debug: Write to log file
		local debugFile = io.open(BASE_DIR .. "\\debug_getdata.log", "a")
		if debugFile then
			debugFile:write(os.date("%c") .. " getdata() called\n")
			debugFile:close()
		end
		
		--If this is the first run then delete the getdata.txt and sendcommand.txt files
		if delete_Files == 1 then
			deleteFiles() --Delete old data first.
		end
		counter = counter + 1
		if counter >= delay then
			local isEngine = Call("GetIsEngineWithKey")
			if debugFile then
				local debugFile2 = io.open(BASE_DIR .. "\\debug_getdata.log", "a")
				if debugFile2 then
					debugFile2:write(os.date("%c") .. " counter >= delay, isEngine: " .. tostring(isEngine) .. "\n")
					debugFile2:close()
				end
			end
			if isEngine == 1 then --Check we are driving the train.
				GetSpeedInfo()
				GetControlData () -- Extract data for controls only.
				GetSpeedLimits () -- Get current & next speed limits as well as distance to next speed limit.
				WriteData () -- Write the data extracted by GetControlData() to GetData.txt.
				SendData () -- Reads 'SendCommand.txt' file generated by 'TS2015 Raildriver Interface.exe' & passes data back to TS2015.
			end
			counter = 0
			gData = ""
		end
	end)
	
	if not success then
		-- Log error but don't crash - write to error file
		local errFile = io.open(GETDATA_ERROR_PATH, "a")
		if errFile then
			errFile:write(os.date("%c") .. " Error in getdata(): " .. tostring(err) .. "\n")
			errFile:close()
		end
	end
end

function GetSpeedInfo()
	local data = "" --Data storage for data to write to output file
	local ControlType = "Speed"
	local ControlName = ""
	local ControlMin = 0
	local ControlMax = 0
	local ControlValue = 0
	
	if Call("ControlExists", "SpeedometerMPH", 0) == 1 then
		speedoType = 1
		ControlName = "SpeedoType"
		ControlMin = 0
		ControlMax = 2 --Call("GetControlMaximum", "SpeedometerMPH", 0)
		ControlValue = 1 -- MPH
		data = data.."ControlType:"..ControlType.."\n"
		data = data .."ControlName:"..ControlName.."\n"
		data = data .."ControlMin:"..ControlMin.."\n"
		data = data .."ControlMax:"..ControlMax.."\n"
		data = data .."ControlValue:"..ControlValue.."\n"
	elseif Call("ControlExists", "MySpeedometerMPH", 0) == 1 then
		speedoType = 1
		ControlName = "SpeedoType"
		ControlMin = 0
		ControlMax = 2 --Call("GetControlMaximum", "MySpeedometerMPH", 0)
		ControlValue = 1 -- MPH
		data = data.."ControlType:"..ControlType.."\n"
		data = data .."ControlName:"..ControlName.."\n"
		data = data .."ControlMin:"..ControlMin.."\n"
		data = data .."ControlMax:"..ControlMax.."\n"
		data = data .."ControlValue:"..ControlValue.."\n"
	elseif Call("ControlExists", "SpeedometerKPH", 0) == 1 then
		speedoType = 2
		ControlName = "SpeedoType"
		ControlMin = 0
		ControlMax = 2 --Call("GetControlMaximum", "SpeedometerKPH", 0)
		ControlValue = 2 -- KPH
		data = data.."ControlType:"..ControlType.."\n"
		data = data .."ControlName:"..ControlName.."\n"
		data = data .."ControlMin:"..ControlMin.."\n"
		data = data .."ControlMax:"..ControlMax.."\n"
		data = data .."ControlValue:"..ControlValue.."\n"
	elseif Call("ControlExists", "MySpeedometerKPH", 0) == 1 then
		speedoType = 2
		ControlName = "SpeedoType"
		ControlMin = 0
		ControlMax = 2 --Call("GetControlMaximum", "MySpeedometerKPH", 0)
		ControlValue = 2 -- KPH
		data = data.."ControlType:"..ControlType.."\n"
		data = data .."ControlName:"..ControlName.."\n"
		data = data .."ControlMin:"..ControlMin.."\n"
		data = data .."ControlMax:"..ControlMax.."\n"
		data = data .."ControlValue:"..ControlValue.."\n"
	else
		speedoType = 0
		ControlName = "SpeedoType"
		ControlMin = 0
		ControlMax = 0
		ControlValue = 0 -- No Speedo Fitted
		data = data.."ControlType:"..ControlType.."\n"
		data = data .."ControlName:"..ControlName.."\n"
		data = data .."ControlMin:"..ControlMin.."\n"
		data = data .."ControlMax:"..ControlMax.."\n"
		data = data .."ControlValue:"..ControlValue.."\n"
	end

	ControlName = "CurrentSpeed"
	ControlMin = 0
	--ControlMax = 3000
	ControlValue = Call("GetSpeed")
	
	data = data.."ControlType:"..ControlType.."\n"
	data = data .."ControlName:"..ControlName.."\n"
	data = data .."ControlMin:"..ControlMin.."\n"
	data = data .."ControlMax:"..ControlMax.."\n"
	data = data .."ControlValue:"..ControlValue.."\n"
	gData = gData ..data
end

function GetControlData()

	local data = "" --Data storage for data to write to output file
	local ControlType = "Speed"
	local ControlName = ""
	local ControlMin = 0
	local ControlMax = 0
	local ControlValue = 0
	
	ControlType = "TimeOfDay"
	ControlName = "TimeOfDay"
	ControlMin = 0
	ControlMax = 0
	ControlValue = SysCall("ScenarioManager:GetTimeOfDay")
	data = data.."ControlType:"..ControlType.."\n"
	data = data .."ControlName:"..ControlName.."\n"
	data = data .."ControlMin:"..ControlMin.."\n"
	data = data .."ControlMax:"..ControlMax.."\n"
	data = data .."ControlValue:"..ControlValue.."\n"
	
	ControlType = "_Acceleration"
	ControlName = "Acceleration"
	ControlMin = 0
	ControlMax = 0
	ControlValue = Call("GetAcceleration")
	data = data.."ControlType:"..ControlType.."\n"
	data = data .."ControlName:"..ControlName.."\n"
	data = data .."ControlMin:"..ControlMin.."\n"
	data = data .."ControlMax:"..ControlMax.."\n"
	data = data .."ControlValue:"..ControlValue.."\n"
	
	ControlType = "_Gradient"
	ControlName = "Gradient"
	ControlMin = 0
	ControlMax = 0
	ControlValue = Call("GetGradient")
	data = data.."ControlType:"..ControlType.."\n"
	data = data .."ControlName:"..ControlName.."\n"
	data = data .."ControlMin:"..ControlMin.."\n"
	data = data .."ControlMax:"..ControlMax.."\n"
	data = data .."ControlValue:"..ControlValue.."\n"
	
	local TenderWaterCapacity = Call("GetTenderWaterCapacity")
	if TenderWaterCapacity then
		ControlType = "_TenderWaterCapacity"
		ControlName = "TenderWaterCapacity"
		ControlMin = 0
		ControlMax = 0
		ControlValue = TenderWaterCapacity
		data = data.."ControlType:"..ControlType.."\n"
		data = data .."ControlName:"..ControlName.."\n"
		data = data .."ControlMin:"..ControlMin.."\n"
		data = data .."ControlMax:"..ControlMax.."\n"
		data = data .."ControlValue:"..ControlValue.."\n"
	end
	
	local TenderWaterCurrent = Call("GetTenderWaterCurrent")
	if TenderWaterCurrent then
		ControlType = "_TenderWaterLevel"
		ControlName = "TenderWaterLevel"
		ControlMin = 0
		ControlMax = 0
		ControlValue = TenderWaterCurrent
		data = data.."ControlType:"..ControlType.."\n"
		data = data .."ControlName:"..ControlName.."\n"
		data = data .."ControlMin:"..ControlMin.."\n"
		data = data .."ControlMax:"..ControlMax.."\n"
		data = data .."ControlValue:"..ControlValue.."\n"
	end
	
	local FuelLevel = Call("GetFuelLevel")
	if FuelLevel then
		ControlType = "_FuelLevel"
		ControlName = "FuelLevel"
		ControlMin = 0 -- Call("GetControlMinimum", "GetFuelLevel", 0) 
		ControlMax = 0 --Call("GetControlMaximum", "GetFuelLevel", 0)
		ControlValue = string.format("%1.3f",FuelLevel)
		data = data.."ControlType:"..ControlType.."\n"
		data = data .."ControlName:"..ControlName.."\n"
		data = data .."ControlMin:"..ControlMin.."\n"
		data = data .."ControlMax:"..ControlMax.."\n"
		data = data .."ControlValue:"..ControlValue.."\n"
	end
	
	local FireboxMass = Call("GetFireboxMass")
	if FireboxMass then
		ControlType = "_FireboxMass"
		ControlName = "FireboxMass"
		ControlMin = 0
		ControlMax = 0
		ControlValue = FireboxMass -- Call("GetFireboxMass") -- string.format("%1.3f",Call("GetFireboxMass"))
		data = data.."ControlType:"..ControlType.."\n"
		data = data .."ControlName:"..ControlName.."\n"
		data = data .."ControlMin:"..ControlMin.."\n"
		data = data .."ControlMax:"..ControlMax.."\n"
		data = data .."ControlValue:"..ControlValue.."\n"
	end
	
	-- Add more critical engine and control telemetry
	-- Ensure we always provide an RPM value in GetData
	local rpm_val = nil
	if Call("ControlExists", "RPM", 0) == 1 then
		rpm_val = Call("GetControlValue", "RPM", 0)
	end
	-- If RPM not present or zero, compute a fallback from throttle/regulator
	if (not rpm_val or rpm_val == 0) then
		local reg = Call("GetControlValue", "Regulator", 0) or 0
		local vth = Call("GetControlValue", "VirtualThrottle", 0) or 0
		local throttle = reg > 0 and reg or vth
		rpm_val = throttle * 5000  -- default engine max RPM
	end
	ControlType = "_RPM"
	ControlName = "RPM"
	ControlMin = 0
	ControlMax = 5000
	ControlValue = string.format("%.1f", rpm_val)
	data = data.."ControlType:"..ControlType.."\n"
		data = data .."ControlName:"..ControlName.."\n"
		data = data .."ControlMin:"..ControlMin.."\n"
		data = data .."ControlMax:"..ControlMax.."\n"
		data = data .."ControlValue:"..ControlValue.."\n"

	-- Add RPMSource for diagnostics: 1=reported by engine, 2=inferred from throttle
	local rpm_source = (Call("ControlExists", "RPM", 0) == 1) and 1 or 2
	ControlType = "_RPMSource"
	ControlName = "RPMSource"
	ControlMin = 0
	ControlMax = 2
	ControlValue = rpm_source
	data = data .."ControlType:"..ControlType.."\n"
	data = data .."ControlName:"..ControlName.."\n"
	data = data .."ControlMin:"..ControlMin.."\n"
	data = data .."ControlMax:"..ControlMax.."\n"
	data = data .."ControlValue:"..ControlValue.."\n"
	
	local TractiveEffort = Call("GetControlValue", "TractiveEffort", 0)
	if TractiveEffort then
		ControlType = "_TractiveEffort"
		ControlName = "TractiveEffort"
		ControlMin = -1000
		ControlMax = 1000
		ControlValue = string.format("%.1f", TractiveEffort)
		data = data.."ControlType:"..ControlType.."\n"
		data = data .."ControlName:"..ControlName.."\n"
		data = data .."ControlMin:"..ControlMin.."\n"
		data = data .."ControlMax:"..ControlMax.."\n"
		data = data .."ControlValue:"..ControlValue.."\n"
	end
	
	local Ammeter = Call("GetControlValue", "Ammeter", 0)
	if Ammeter then
		ControlType = "_Ammeter"
		ControlName = "Ammeter"
		ControlMin = -800
		ControlMax = 1500
		ControlValue = string.format("%.1f", Ammeter)
		data = data.."ControlType:"..ControlType.."\n"
		data = data .."ControlName:"..ControlName.."\n"
		data = data .."ControlMin:"..ControlMin.."\n"
		data = data .."ControlMax:"..ControlMax.."\n"
		data = data .."ControlValue:"..ControlValue.."\n"
	end
	
	local EngineBrakeControl = Call("GetControlValue", "EngineBrakeControl", 0)
	if EngineBrakeControl then
		ControlType = "_EngineBrakeControl"
		ControlName = "EngineBrakeControl"
		ControlMin = 0
		ControlMax = 1
		ControlValue = string.format("%.3f", EngineBrakeControl)
		data = data.."ControlType:"..ControlType.."\n"
		data = data .."ControlName:"..ControlName.."\n"
		data = data .."ControlMin:"..ControlMin.."\n"
		data = data .."ControlMax:"..ControlMax.."\n"
		data = data .."ControlValue:"..ControlValue.."\n"
	end
	
	local Regulator = Call("GetControlValue", "Regulator", 0)
	if Regulator then
		ControlType = "_Regulator"
		ControlName = "Regulator"
		ControlMin = 0
		ControlMax = 1
		ControlValue = string.format("%.3f", Regulator)
		data = data.."ControlType:"..ControlType.."\n"
		data = data .."ControlName:"..ControlName.."\n"
		data = data .."ControlMin:"..ControlMin.."\n"
		data = data .."ControlMax:"..ControlMax.."\n"
		data = data .."ControlValue:"..ControlValue.."\n"
	end

	-- Additional controls used by dashboard/backend: VirtualThrottle, VirtualBrake, SimpleThrottle, Headlights, Signal aspects, Distance
	local VirtualThrottle = Call("GetControlValue", "VirtualThrottle", 0)
	if VirtualThrottle then
		ControlType = "_VirtualThrottle"
		ControlName = "VirtualThrottle"
		ControlMin = 0
		ControlMax = 1
		ControlValue = string.format("%.3f", VirtualThrottle)
		data = data.."ControlType:"..ControlType.."\n"
		data = data .."ControlName:"..ControlName.."\n"
		data = data .."ControlMin:"..ControlMin.."\n"
		data = data .."ControlMax:"..ControlMax.."\n"
		data = data .."ControlValue:"..ControlValue.."\n"
	end

	local VirtualBrake = Call("GetControlValue", "VirtualBrake", 0)
	if VirtualBrake then
		ControlType = "_VirtualBrake"
		ControlName = "VirtualBrake"
		ControlMin = 0
		ControlMax = 1
		ControlValue = string.format("%.3f", VirtualBrake)
		data = data.."ControlType:"..ControlType.."\n"
		data = data .."ControlName:"..ControlName.."\n"
		data = data .."ControlMin:"..ControlMin.."\n"
		data = data .."ControlMax:"..ControlMax.."\n"
		data = data .."ControlValue:"..ControlValue.."\n"
	end

	local SimpleThrottle = Call("GetControlValue", "SimpleThrottle", 0)
	if SimpleThrottle then
		ControlType = "_SimpleThrottle"
		ControlName = "SimpleThrottle"
		ControlMin = 0
		ControlMax = 1
		ControlValue = string.format("%.3f", SimpleThrottle)
		data = data.."ControlType:"..ControlType.."\n"
		data = data .."ControlName:"..ControlName.."\n"
		data = data .."ControlMin:"..ControlMin.."\n"
		data = data .."ControlMax:"..ControlMax.."\n"
		data = data .."ControlValue:"..ControlValue.."\n"
	end

	local Headlights = Call("GetControlValue", "Headlights", 0)
	if Headlights then
		ControlType = "_Headlights"
		ControlName = "Headlights"
		ControlMin = 0
		ControlMax = 1
		ControlValue = string.format("%.0f", Headlights)
		data = data.."ControlType:"..ControlType.."\n"
		data = data .."ControlName:"..ControlName.."\n"
		data = data .."ControlMin:"..ControlMin.."\n"
		data = data .."ControlMax:"..ControlMax.."\n"
		data = data .."ControlValue:"..ControlValue.."\n"
	end

	local SignalAspect = Call("GetControlValue", "SignalAspect", 0)
	if SignalAspect then
		ControlType = "_Signal"
		ControlName = "SignalAspect"
		ControlMin = -1
		ControlMax = 10
		ControlValue = string.format("%d", SignalAspect)
		data = data.."ControlType:"..ControlType.."\n"
		data = data .."ControlName:"..ControlName.."\n"
		data = data .."ControlMin:"..ControlMin.."\n"
		data = data .."ControlMax:"..ControlMax.."\n"
		data = data .."ControlValue:"..ControlValue.."\n"
	end

	local KVB_SignalAspect = Call("GetControlValue", "KVB_SignalAspect", 0)
	if KVB_SignalAspect then
		ControlType = "_SignalAdvanced"
		ControlName = "KVB_SignalAspect"
		ControlMin = -1
		ControlMax = 10
		ControlValue = string.format("%d", KVB_SignalAspect)
		data = data.."ControlType:"..ControlType.."\n"
		data = data .."ControlName:"..ControlName.."\n"
		data = data .."ControlMin:"..ControlMin.."\n"
		data = data .."ControlMax:"..ControlMax.."\n"
		data = data .."ControlValue:"..ControlValue.."\n"
	end

	local DistanceTravelled = Call("GetControlValue", "DistanceTravelled", 0)
	if DistanceTravelled then
		ControlType = "_Distance"
		ControlName = "DistanceTravelled"
		ControlMin = 0
		ControlMax = 100000000
		ControlValue = string.format("%.1f", DistanceTravelled)
		data = data.."ControlType:"..ControlType.."\n"
		data = data .."ControlName:"..ControlName.."\n"
		data = data .."ControlMin:"..ControlMin.."\n"
		data = data .."ControlMax:"..ControlMax.."\n"
		data = data .."ControlValue:"..ControlValue.."\n"
	end

	local Reverser = Call("GetControlValue", "Reverser", 0)
	if Reverser then
		ControlType = "_Reverser"
		ControlName = "Reverser"
		ControlMin = -1
		ControlMax = 1
		ControlValue = string.format("%.1f", Reverser)
		data = data.."ControlType:"..ControlType.."\n"
		data = data .."ControlName:"..ControlName.."\n"
		data = data .."ControlMin:"..ControlMin.."\n"
		data = data .."ControlMax:"..ControlMax.."\n"
		data = data .."ControlValue:"..ControlValue.."\n"
	end
	
	local TrainBrakeControl = Call("GetControlValue", "TrainBrakeControl", 0)
	if TrainBrakeControl then
		ControlType = "_TrainBrakeControl"
		ControlName = "TrainBrakeControl"
		ControlMin = 0
		ControlMax = 1
		ControlValue = string.format("%.3f", TrainBrakeControl)
		data = data.."ControlType:"..ControlType.."\n"
		data = data .."ControlName:"..ControlName.."\n"
		data = data .."ControlMin:"..ControlMin.."\n"
		data = data .."ControlMax:"..ControlMax.."\n"
		data = data .."ControlValue:"..ControlValue.."\n"
	end
	
	local DynamicBrake = Call("GetControlValue", "DynamicBrake", 0)
	if DynamicBrake then
		ControlType = "_DynamicBrake"
		ControlName = "DynamicBrake"
		ControlMin = 0
		ControlMax = 1
		ControlValue = string.format("%.3f", DynamicBrake)
		data = data.."ControlType:"..ControlType.."\n"
		data = data .."ControlName:"..ControlName.."\n"
		data = data .."ControlMin:"..ControlMin.."\n"
		data = data .."ControlMax:"..ControlMax.."\n"
		data = data .."ControlValue:"..ControlValue.."\n"
	end
	
	local HandBrake = Call("GetControlValue", "HandBrake", 0)
	if HandBrake then
		ControlType = "_HandBrake"
		ControlName = "HandBrake"
		ControlMin = 0
		ControlMax = 1
		ControlValue = string.format("%.3f", HandBrake)
		data = data.."ControlType:"..ControlType.."\n"
		data = data .."ControlName:"..ControlName.."\n"
		data = data .."ControlMin:"..ControlMin.."\n"
		data = data .."ControlMax:"..ControlMax.."\n"
		data = data .."ControlValue:"..ControlValue.."\n"
	end
	
	local EmergencyBrake = Call("GetControlValue", "EmergencyBrake", 0)
	if EmergencyBrake then
		ControlType = "_EmergencyBrake"
		ControlName = "EmergencyBrake"
		ControlMin = 0
		ControlMax = 1
		ControlValue = string.format("%.1f", EmergencyBrake)
		data = data.."ControlType:"..ControlType.."\n"
		data = data .."ControlName:"..ControlName.."\n"
		data = data .."ControlMin:"..ControlMin.."\n"
		data = data .."ControlMax:"..ControlMax.."\n"
		data = data .."ControlValue:"..ControlValue.."\n"
	end
	
	local CompressorState = Call("GetControlValue", "CompressorState", 0)
	if CompressorState then
		ControlType = "_CompressorState"
		ControlName = "CompressorState"
		ControlMin = 0
		ControlMax = 1
		ControlValue = string.format("%.1f", CompressorState)
		data = data.."ControlType:"..ControlType.."\n"
		data = data .."ControlName:"..ControlName.."\n"
		data = data .."ControlMin:"..ControlMin.."\n"
		data = data .."ControlMax:"..ControlMax.."\n"
		data = data .."ControlValue:"..ControlValue.."\n"
	end
	
	local Wheelslip = Call("GetControlValue", "Wheelslip", 0)
	if Wheelslip then
		ControlType = "_Wheelslip"
		ControlName = "Wheelslip"
		ControlMin = 0
		ControlMax = 2
		ControlValue = string.format("%.1f", Wheelslip)
		data = data.."ControlType:"..ControlType.."\n"
		data = data .."ControlName:"..ControlName.."\n"
		data = data .."ControlMin:"..ControlMin.."\n"
		data = data .."ControlMax:"..ControlMax.."\n"
		data = data .."ControlValue:"..ControlValue.."\n"
	end
	
	-- Brake Pressure Readings
	local AirBrakePipePressurePSI = Call("GetControlValue", "AirBrakePipePressurePSI", 0)
	if AirBrakePipePressurePSI then
		ControlType = "_AirBrakePipePressurePSI"
		ControlName = "AirBrakePipePressurePSI"
		ControlMin = 0
		ControlMax = 160
		ControlValue = string.format("%.1f", AirBrakePipePressurePSI)
		data = data.."ControlType:"..ControlType.."\n"
		data = data .."ControlName:"..ControlName.."\n"
		data = data .."ControlMin:"..ControlMin.."\n"
		data = data .."ControlMax:"..ControlMax.."\n"
		data = data .."ControlValue:"..ControlValue.."\n"
	end
	
	local LocoBrakeCylinderPressurePSI = Call("GetControlValue", "LocoBrakeCylinderPressurePSI", 0)
	if LocoBrakeCylinderPressurePSI then
		ControlType = "_LocoBrakeCylinderPressurePSI"
		ControlName = "LocoBrakeCylinderPressurePSI"
		ControlMin = 0
		ControlMax = 160
		ControlValue = string.format("%.1f", LocoBrakeCylinderPressurePSI)
		data = data.."ControlType:"..ControlType.."\n"
		data = data .."ControlName:"..ControlName.."\n"
		data = data .."ControlMin:"..ControlMin.."\n"
		data = data .."ControlMax:"..ControlMax.."\n"
		data = data .."ControlValue:"..ControlValue.."\n"
	end
	
	local TrainBrakeCylinderPressurePSI = Call("GetControlValue", "TrainBrakeCylinderPressurePSI", 0)
	if TrainBrakeCylinderPressurePSI then
		ControlType = "_TrainBrakeCylinderPressurePSI"
		ControlName = "TrainBrakeCylinderPressurePSI"
		ControlMin = 0
		ControlMax = 160
		ControlValue = string.format("%.1f", TrainBrakeCylinderPressurePSI)
		data = data.."ControlType:"..ControlType.."\n"
		data = data .."ControlName:"..ControlName.."\n"
		data = data .."ControlMin:"..ControlMin.."\n"
		data = data .."ControlMax:"..ControlMax.."\n"
		data = data .."ControlValue:"..ControlValue.."\n"
	end
	
	local EqReservoirPressurePSIAdvanced = Call("GetControlValue", "EqReservoirPressurePSIAdvanced", 0)
	if EqReservoirPressurePSIAdvanced then
		ControlType = "_EqReservoirPressurePSIAdvanced"
		ControlName = "EqReservoirPressurePSIAdvanced"
		ControlMin = 0
		ControlMax = 160
		ControlValue = string.format("%.1f", EqReservoirPressurePSIAdvanced)
		data = data.."ControlType:"..ControlType.."\n"
		data = data .."ControlName:"..ControlName.."\n"
		data = data .."ControlMin:"..ControlMin.."\n"
		data = data .."ControlMax:"..ControlMax.."\n"
		data = data .."ControlValue:"..ControlValue.."\n"
	end
	
	local MainReservoirPressurePSIDisplayed = Call("GetControlValue", "MainReservoirPressurePSIDisplayed", 0)
	if MainReservoirPressurePSIDisplayed then
		ControlType = "_MainReservoirPressurePSIDisplayed"
		ControlName = "MainReservoirPressurePSIDisplayed"
		ControlMin = 0
		ControlMax = 160
		ControlValue = string.format("%.1f", MainReservoirPressurePSIDisplayed)
		data = data.."ControlType:"..ControlType.."\n"
		data = data .."ControlName:"..ControlName.."\n"
		data = data .."ControlMin:"..ControlMin.."\n"
		data = data .."ControlMax:"..ControlMax.."\n"
		data = data .."ControlValue:"..ControlValue.."\n"
	end
	
	local AirBrakePipePressurePSIDisplayed = Call("GetControlValue", "AirBrakePipePressurePSIDisplayed", 0)
	if AirBrakePipePressurePSIDisplayed then
		ControlType = "_AirBrakePipePressurePSIDisplayed"
		ControlName = "AirBrakePipePressurePSIDisplayed"
		ControlMin = 0
		ControlMax = 160
		ControlValue = string.format("%.1f", AirBrakePipePressurePSIDisplayed)
		data = data.."ControlType:"..ControlType.."\n"
		data = data .."ControlName:"..ControlName.."\n"
		data = data .."ControlMin:"..ControlMin.."\n"
		data = data .."ControlMax:"..ControlMax.."\n"
		data = data .."ControlValue:"..ControlValue.."\n"
	end
	
	local AuxReservoirPressure = Call("GetControlValue", "AuxReservoirPressure", 0)
	if AuxReservoirPressure then
		ControlType = "_AuxReservoirPressure"
		ControlName = "AuxReservoirPressure"
		ControlMin = 0
		ControlMax = 90
		ControlValue = string.format("%.1f", AuxReservoirPressure)
		data = data.."ControlType:"..ControlType.."\n"
		data = data .."ControlName:"..ControlName.."\n"
		data = data .."ControlMin:"..ControlMin.."\n"
		data = data .."ControlMax:"..ControlMax.."\n"
		data = data .."ControlValue:"..ControlValue.."\n"
	end
	
	local BrakePipePressureTailEnd = Call("GetControlValue", "BrakePipePressureTailEnd", 0)
	if BrakePipePressureTailEnd then
		ControlType = "_BrakePipePressureTailEnd"
		ControlName = "BrakePipePressureTailEnd"
		ControlMin = 0
		ControlMax = 90
		ControlValue = string.format("%.1f", BrakePipePressureTailEnd)
		data = data.."ControlType:"..ControlType.."\n"
		data = data .."ControlName:"..ControlName.."\n"
		data = data .."ControlMin:"..ControlMin.."\n"
		data = data .."ControlMax:"..ControlMax.."\n"
		data = data .."ControlValue:"..ControlValue.."\n"
	end
	
	local LocoBrakeCylinderPressurePSIDisplayed = Call("GetControlValue", "LocoBrakeCylinderPressurePSIDisplayed", 0)
	if LocoBrakeCylinderPressurePSIDisplayed then
		ControlType = "_LocoBrakeCylinderPressurePSIDisplayed"
		ControlName = "LocoBrakeCylinderPressurePSIDisplayed"
		ControlMin = 0
		ControlMax = 160
		ControlValue = string.format("%.1f", LocoBrakeCylinderPressurePSIDisplayed)
		data = data.."ControlType:"..ControlType.."\n"
		data = data .."ControlName:"..ControlName.."\n"
		data = data .."ControlMin:"..ControlMin.."\n"
		data = data .."ControlMax:"..ControlMax.."\n"
		data = data .."ControlValue:"..ControlValue.."\n"
	end
	
	local LocoBrakeCylinderPressurePSIAdvanced = Call("GetControlValue", "LocoBrakeCylinderPressurePSIAdvanced", 0)
	if LocoBrakeCylinderPressurePSIAdvanced then
		ControlType = "_LocoBrakeCylinderPressurePSIAdvanced"
		ControlName = "LocoBrakeCylinderPressurePSIAdvanced"
		ControlMin = 0
		ControlMax = 160
		ControlValue = string.format("%.1f", LocoBrakeCylinderPressurePSIAdvanced)
		data = data.."ControlType:"..ControlType.."\n"
		data = data .."ControlName:"..ControlName.."\n"
		data = data .."ControlMin:"..ControlMin.."\n"
		data = data .."ControlMax:"..ControlMax.."\n"
		data = data .."ControlValue:"..ControlValue.."\n"
	end

	gData = gData ..data
end

function GetSpeedLimits ()
	local data = "" --Data storage for data to write to output file
	local ControlType = "SpeedLimit"
	local ControlName = ""
	local ControlMin = 0
	local ControlMax = 0
	local ControlValue = ""
	
	ControlValue = Call( "GetCurrentSpeedLimit" )
	if (speedoType <= 1) then
		ControlValue = string.format("%1.1f", ControlValue * MPH)
	elseif (speedoType == 2) then 
		ControlValue = string.format("%1.1f", ControlValue * KPH)
	end
	ControlName = "CurrentSpeedLimit"
	ControlMin = 0
	ControlMax = 300
	data = data.."ControlType:"..ControlType.."\n"
	data = data .."ControlName:"..ControlName.."\n"
	data = data .."ControlMin:"..ControlMin.."\n"
	data = data .."ControlMax:"..ControlMax.."\n"
	data = data .."ControlValue:"..ControlValue.."\n"

	NextSpeedLimitType, NextSpeedLimitSpeed, NextSpeedLimitDistance = Call("GetNextSpeedLimit", 0)

	ControlValue = NextSpeedLimitType or 0
	ControlName = "NextSpeedLimitType"
	ControlMin = 0
	ControlMax = 10
	data = data.."ControlType:"..ControlType.."\n"
	data = data .."ControlName:"..ControlName.."\n"
	data = data .."ControlMin:"..ControlMin.."\n"
	data = data .."ControlMax:"..ControlMax.."\n"
	data = data .."ControlValue:"..ControlValue.."\n"
	-- currentvalues[ControlName] = ControlValue

	ControlValue = NextSpeedLimitSpeed or 0
	ControlName = "NextSpeedLimitSpeed"
	ControlMin = 0
	ControlMax = 500
	-- Check speedlimit does not exceed 1000 as some tracks report no speed limit as very high value
	-- 1225016488463523100000000000000000000000.0 which crashes the C# program
	if (ControlValue and ControlValue >= 1000) then 
		ControlValue = 0
	end
	
	if (speedoType <= 1 ) then 
		ControlValue = (ControlValue or 0) * MPH
	elseif (speedoType == 2) then 
		ControlValue = (ControlValue or 0) * KPH
	end
	ControlValue = string.format("%1.1f", ControlValue)
	data = data.."ControlType:"..ControlType.."\n"
	data = data .."ControlName:"..ControlName.."\n"
	data = data .."ControlMin:"..ControlMin.."\n"
	data = data .."ControlMax:"..ControlMax.."\n"
	data = data .."ControlValue:"..ControlValue.."\n"
	-- currentvalues[ControlName] = ControlValue

	ControlValue = string.format("%d", NextSpeedLimitDistance or 0)
	ControlName = "NextSpeedLimitDistance"
	ControlMin = 0
	ControlMax = 10000
	data = data.."ControlType:"..ControlType.."\n"
	data = data .."ControlName:"..ControlName.."\n"
	data = data .."ControlMin:"..ControlMin.."\n"
	data = data .."ControlMax:"..ControlMax.."\n"
	data = data .."ControlValue:"..ControlValue.."\n"
	-- currentvalues[ControlName] = ControlValue
	
	NextSpeedLimitBackType, NextSpeedLimitBackSpeed, NextSpeedLimitBackDistance = Call("GetNextSpeedLimit", 1)

	ControlValue = NextSpeedLimitBackType or 0
	ControlName = "NextSpeedLimitBackType"
	ControlMin = 0
	ControlMax = 10
	data = data.."ControlType:"..ControlType.."\n"
	data = data .."ControlName:"..ControlName.."\n"
	data = data .."ControlMin:"..ControlMin.."\n"
	data = data .."ControlMax:"..ControlMax.."\n"
	data = data .."ControlValue:"..ControlValue.."\n"
	-- currentvalues[ControlName] = ControlValue

	ControlValue = NextSpeedLimitBackSpeed or 0
	ControlName = "NextSpeedLimitBackSpeed"
	ControlMin = 0
	ControlMax = 500
	-- Check speedlimit does not exceed 1000 as some tracks report no speed limit as very high value
	-- 1225016488463523100000000000000000000000.0 which crashes the C# program
	if (ControlValue and ControlValue >= 1000) then 
		ControlValue = 0
	end
	
	if (speedoType <= 1 ) then 
		ControlValue = ControlValue * MPH
	elseif (speedoType == 2) then 
		ControlValue = ControlValue * KPH
	end
	ControlValue = string.format("%1.1f", ControlValue)
	data = data.."ControlType:"..ControlType.."\n"
	data = data .."ControlName:"..ControlName.."\n"
	data = data .."ControlMin:"..ControlMin.."\n"
	data = data .."ControlMax:"..ControlMax.."\n"
	data = data .."ControlValue:"..ControlValue.."\n"
	-- currentvalues[ControlName] = ControlValue

	ControlValue = string.format("%d", NextSpeedLimitBackDistance or 0)
	ControlName = "NextSpeedLimitBackDistance"
	ControlMin = 0
	ControlMax = 10000
	data = data.."ControlType:"..ControlType.."\n"
	data = data .."ControlName:"..ControlName.."\n"
	data = data .."ControlMin:"..ControlMin.."\n"
	data = data .."ControlMax:"..ControlMax.."\n"
	data = data .."ControlValue:"..ControlValue.."\n"
	gData = gData ..data
				
end
	
function WriteData ()
	local success, err = pcall(function()
		gData = gData .."ControlType:SimulationTime".."\n"
		gData = gData .."ControlName:SimulationTime".."\n"
		gData = gData .."ControlMin:0".."\n"
		gData = gData .."ControlMax:0".."\n"
		gData = gData .."ControlValue:"..Call( "GetSimulationTime", 0 ).."\n"

		-- Debug: Log before writing
		local debugFile = io.open(BASE_DIR .. "\\debug_getdata.log", "a")
		if debugFile then
			debugFile:write(os.date("%c") .. " Writing data, gData length: " .. tostring(#gData) .. "\n")
			debugFile:close()
		end
		
		-- Write data to file atomically (use GETDATA_PATH)
		local tmpfile = GETDATA_PATH .. ".tmp"
		local ftmp, ferr = io.open(tmpfile, "w")
		if ftmp then
			ftmp:write(gData)
			ftmp:flush()
			ftmp:close()
			-- replace atomically: remove final if exists then rename
			local final_exists = io.open(GETDATA_PATH, "r")
			if final_exists then
				final_exists:close()
				pcall(function() os.remove(GETDATA_PATH) end)
			end
			local ok, rename_err = pcall(function() os.rename(tmpfile, GETDATA_PATH) end)
			if not ok then
				-- fallback attempt
				pcall(function() os.remove(GETDATA_PATH) end)
				pcall(function() os.rename(tmpfile, GETDATA_PATH) end)
			end
		else
			-- failed to open tmp for writing; record error
			local errFile = io.open(GETDATA_ERROR_PATH, "a")
			if errFile then
				errFile:write(os.date("%c") .. " WriteData failed opening tmp file: " .. tostring(ferr) .. "\n")
				errFile:close()
			end
		end
		--Clear values 
		gData = ""
	end)
	
	if not success then
		local errFile = io.open(GETDATA_ERROR_PATH, "a")
		if errFile then
			errFile:write(os.date("%c") .. " WriteData Error: " .. tostring(err) .. "\n")
			errFile:close()
		end
		gData = "" -- Clear data even on error
	end
end

function SendData ()
	local success, err = pcall(function()
		-- Read file & send data to Railworks
		--1st we read a line from the SendCommand.txt file (try uppercase then lowercase)
		local cmdfile = SENDCOMMAND_PATH
		local file = io.open(cmdfile, "r")
		if not file then
			-- try lowercase legacy filename
			cmdfile = SENDCOMMAND_PATH_LOWER
			file = io.open(cmdfile, "r")
			if not file then
				return -- File doesn't exist, skip command processing
			end
		end
		file:close()
	
		for line in io.lines(cmdfile) do 
			--Check to make sure it isn't a blank line
			if line ~= "" then
				--it isn't blank so create a table(array) to hold the variables
				t = {}
				i = 1
				--Look for the colon(:) in the file that separates the control name
				-- from the value to send
				for str in string.gmatch(line, "[^:]+") do
					--Place the control name in t[1] then increment i
					--and place the value for the control in t[2]
					t[i] = str
					i = i + 1
				end
				
				--Force controls to 0 on first run
				if dataread == 0 and t[1] then
					previousValues[t[1]] = -1
					t[2] = 0
				end

				if t[1] and t[2] then
					if t[1]~= "Wipers" and t[1] ~= "WiperSpeed" and t[1] ~= "swDriverWiper" then
						if previousValues[t[1]] ~= t[2] then
							--Send the command to railworks. The format is:-
							--Call("*:SetControlValue", Control name, 0 (for lead engine), value for the control)
							if OnControlValueChange then
								OnControlValueChange(t[1], 0, tonumber(t[2]))
							else
								Call( "SetControlValue", t[1], 0, tonumber(t[2])) 
							end
							Call("SetControlTargetValue", t[1], 0, tonumber(t[2]))
							previousValues[t[1]] = t[2]
						end
					end
					
					if t[1] == "Wipers" or t[1] == "WiperSpeed" or t[1] == "swDriverWiper" then
						if previousValues[t[1]] ~= t[2] then 
							--Send the command to railworks. The format is:-
							--Call("SetControlValue", Control name, 0 (for lead engine), value for the control)
							if OnControlValueChange then
								OnControlValueChange(t[1], 0, tonumber(t[2]))
							else
								Call( "SetControlValue", t[1], 0, tonumber(t[2])) 
							end
							Call("SetControlTargetValue", t[1], 0, tonumber(t[2]))
						end
						previousValues[t[1]] = t[2]
					end
				end
			end
		end
		dataread = 1
	end)
	
	if not success then
		-- Error reading/sending commands, continue silently
	end
end

function deleteFiles()
	pcall(function()
		os.remove(GETDATA_PATH)
		os.remove(SENDCOMMAND_PATH)
		os.remove(SENDCOMMAND_PATH_LOWER)
	end)
	delete_Files = 0
end